#!/usr/bin/env python

import os
import sys

from archipelago import vlmc as vlmc
from archipelago.common import loadrc

def hooks_log(msg):
    f = open('/var/log/ganeti/hooks.log', 'a')
    f.write("%s\n" % msg)
    f.close()


def archip_premigrate_disk(idx):
    provider = os.getenv("GANETI_INSTANCE_DISK%d_PROVIDER" % idx)
    vol_name = os.getenv("GANETI_INSTANCE_DISK%d_ID" % idx)
    template = os.getenv("GANETI_INSTANCE_DISK%d_TEMPLATE_NAME" % idx)

    if template != 'ext':
        raise Exception("Invalid disk template %s" % template)

    if provider != 'archipelago' and provider != 'vlmc':
        raise Exception("Unknown provider %s" % provider)

    if not vol_name:
        raise Exception("No volume name provided")

    hooks_log("Opening volume %s" % vol_name)
    vlmc.open_volume(name=vol_name)
    hooks_log("Opened volume %s" % vol_name)


def archip_premigrate():
    try:
        count = os.getenv("GANETI_INSTANCE_DISK_COUNT")
        template = os.getenv("GANETI_INSTANCE_DISK_TEMPLATE")
    except:
        return 1

    if template != 'ext':
        return 1

    count = int(count)
    hooks_log("Found %d disks" % count)

    for i in range(0, count):
        try:
            archip_premigrate_disk(i)
        except Exception as e:
            msg = "Failed to open volume %d: %s" % (i, e)
            print msg
            hooks_log(msg)
            return 1

    return 0

if __name__ == '__main__':
    loadrc(None)
    exit(archip_premigrate())

